"""init migrations (add message)

Revision ID: 268bcdfb0c0e
Revises: 
Create Date: 2023-08-03 21:44:38.696675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268bcdfb0c0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
