"""fix nullable param in toxic_level

Revision ID: 920217c0495c
Revises: 4dc3cbe276e2
Create Date: 2023-10-26 20:34:57.491679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920217c0495c'
down_revision = '4dc3cbe276e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
