"""add lucky bool

Revision ID: bdccd84b86e6
Revises: d4e5f6a7b8c9
Create Date: 2026-04-16 22:07:47.688793

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bdccd84b86e6"
down_revision = "d4e5f6a7b8c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_queue_members_queue_id"), "queue_members", ["queue_id"], unique=False
    )
    op.add_column("user", sa.Column("casino_lucky", sa.Boolean(), nullable=False))
    op.alter_column(
        "user", "toxicity_level", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "toxicity_level", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("user", "casino_lucky")
    op.drop_index(op.f("ix_queue_members_queue_id"), table_name="queue_members")
    # ### end Alembic commands ###
