"""initial

Revision ID: f50b6ad6c736
Revises: 
Create Date: 2023-09-29 21:54:23.309087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50b6ad6c736'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sticker_message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('set_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_sticker_message_id'), 'sticker_message', ['id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('sanitary_last', sa.Boolean(), nullable=True),
    sa.Column('penis_size', sa.Integer(), nullable=True),
    sa.Column('last_penis_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index(op.f('ix_sticker_message_id'), table_name='sticker_message')
    op.drop_table('sticker_message')
    # ### end Alembic commands ###
